name: Update README

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *' # Runs every day at midnight

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Update README with GitHub Stats
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          curl -o README.md https://raw.githubusercontent.com/othnielObasi/profile/main/README.md
          sed -i "s/TOKEN_PLACEHOLDER/${{ secrets.GH_PAT }}/g" README.md
          git config --global user.email "othnielobasi@gmail.com"
          git config --global user.name "othnielObasi"
          git add README.md
          git commit -m "Update README with GitHub stats"

      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GH_PAT }}
          branch: main
